# build stage
FROM golang:{{ version }}-alpine3.6 AS build-env
ADD . /src/{{ project_path }}
WORKDIR /src/{{ project_path }}
RUN go build -o app


# test stage
FROM golang:{{ version }}-alpine3.6
WORKDIR /src/{{ project_path }}
RUN go test


# release stage
FROM alpine
WORKDIR /app
EXPOSE 8080
COPY --from=build-env /src/{{ project_path }}/app /app/
ENTRYPOINT ./app