# stage1
FROM {{ version }} AS base
COPY package.json .
RUN npm set progress=false && npm config set depth 0
RUN npm install --only=production
RUN cp -R node_modules prod_node_modules
RUN npm install

# stage 2
FROM base As test
COPY . /app
RUN npm test

# stage 3
FROM base AS release
COPY --from=dependencies /root/app/prod_node_modules /root/app/node_modules
COPY . /app
CMD ['npm','start']